name: shelf_serve
description: >
  This package makes it easy to configure and serve a website and backend with Shelf.
version: 0.0.1
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/rbellens/shelf_serve
dependencies:
  shelf: ">=0.5.7 <0.6.0"
  yaml: ">=2.1.2 <3.0.0"
  yamlicious: any
  args: ">=0.12.2+6 <0.13.0"
  shelf_route: ">=0.11.0+1 <0.12.0"
  shelf_static: ">=0.2.2 <0.3.0"
  shelf_rpc: ">=0.0.3 <0.1.0"
  shelf_proxy: ">=0.1.0+2 <0.2.0"
  shelf_cors: any
  rpc: ">=0.4.0 <0.5.0"
  initialize: any
dependency_overrides:
  quiver: ^0.21.3
dev_dependencies:
  unittest: any
