name: shelf_serve
description: >
  This package makes it easy to configure and serve a website and backend with Shelf.
version: 0.2.3
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/shelf_serve
dependencies:
  shelf: ">=0.6.5 <0.7.0"
  yaml: ">=2.1.2 <3.0.0"
  yamlicious: ">=0.0.4 <0.1.0"
  shelf_route: ">=0.14.2 <0.15.0"
  shelf_static: ">=0.2.4 <0.3.0"
  shelf_rpc: ">=0.0.3 <0.1.0"
  shelf_proxy: ">=0.1.0+2 <0.2.0"
  shelf_cors: ">=0.2.1 <0.3.0"
  rpc: ">=0.5.6+2 <0.6.0"
  unscripted: ">=0.6.2 <0.7.0"
  initialize: ">=0.6.0+5 <0.7.0"
  pubspec: ">=0.0.7 <0.1.0"
dev_dependencies:
  unittest: any
executables:
  shelf_serve: